# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: themattrix/tox

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    parameters:
      octoprint-version:
        type: string

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-<< parameters.octoprint-version >>
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            apt update && apt install -y libjpeg-dev zlib1g-dev
            python -m venv venv
            . venv/bin/activate
            pip install git+https://github.com/foosel/OctoPrint.git@<< parameters.octoprint-version >>
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install pipdeptree

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-<< parameters.octoprint-version >>

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pipdeptree
            python setup.py test coverage
            python -m tox

      - store_artifacts:
          path: htmlcov/
          destination: coverage-report

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              octoprint-version:
                - devel # validate that it works with the tip for next version
                - 1.3.11 # the minimum version allowed via setup.py
